sonar.projectKey=wahyusutejo1986_fincorp
sonar.organization=wahyusutejo1986
sonar.projectName=fincorp

sonar.sources=backend,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/examples/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
